global:
 scrape_interval:     5s # By default, scrape targets every 15 seconds.
 evaluation_interval: 5s # By default, scrape targets every 15 seconds.
 external_labels:
   collector: prometheus@001 
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['127.0.0.2:9090']
rule_urls:
        - 'http://10.104.104.28/accounts/api/v1/rule/' 
        - 'http://10.204.57.246:9333/api/v1/rules' 
#remote_write:
#    - url: http://localhost:9268/write
#remote_read:
#    - url: http://localhost:9268/read
