global:
 scrape_interval:     5s # By default, scrape targets every 15 seconds.
 evaluation_interval: 5s # By default, scrape targets every 15 seconds.
 external_labels:
   collector: prometheus@001 
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['127.0.0.1:9090']
        
#remote_read:
#- url: "http://127.0.0.1:9201/read"
# remote_write:
#   - url: "http://127.0.0.1:9201/write"
